version: "3.9"
services:
  game:
    build: .
    ports:
      - "6080:80"
      - "42069:42074/udp"
      - "42069:42074/tcp"
      - "5900:5900"
      - "8000:8000"
    volumes:
      - type: bind
        source: ./files 
        target: /root/.config/BoringManRewrite