version: "3.9"
services:
  game:
    image: coyotebm/bm-server-api
    build: .
    ports:
      - "6080:80"
      - "42069-42074:42069-42074/udp"
      - "42069-42074:42069-42074/tcp"
      - "8000:8000"
    volumes:
      - type: bind
        source: ./files 
        target: /root/.config/BoringManRewrite